### ISSUE TITLE
Are there any plans to develop a fabric version?

### ISSUE THREAD

**Issue by Chikage0o0** [thebrightspark/AsyncLocator#1]

**Comment by thebrightspark** [comment]
Hi, yes I have been considering releasing versions for Fabric too. I just need to sit down and figure it iout at some point soon as I've not used Fabric before. But it should hopefully be relatively easy, as the mod already uses Mixins for the most part.

**Comment by thebrightspark** [comment]
Fabric versions are out now, so closing this 😄
