### ISSUE TITLE
Can be marked as 1.20.2 compatible

### ISSUE THREAD

**Issue by sternschnaube** [thebrightspark/AsyncLocator#14]

**Comment by thebrightspark** [comment]
Hey, I'm not sure what's wanted here? I haven't *not* marked the mod as 1.20.2 compatible 😅 
As far as I'm aware I've only labelled it as `1.20`, and it should be allowed for any 1.20.x version

**Comment by sternschnaube** [comment]
Mod isn't listed as 1.20.2 compatible on Modrinth, but it seems to work. That's it 😊

**Comment by thebrightspark** [comment]
Oh I see you're right! I've adjusted that now, thanks for letting me know!
