### ISSUE TITLE
[1.18.2]  Async doesn't work for IDAS

### ISSUE THREAD

**Issue by Reshy** [thebrightspark/AsyncLocator#4]
The async multithreading doesn't seem to work for Integrated Dungeons and Structures, this can be tested by rapidly cycling a cartographer with the IDAS mod installed.

**Comment by thebrightspark** [comment]
Hey @Reshy, I'm not familiar with that mod, however if this Cartographer is an item from that mod then Async Locator won't natively support it. Support will need to be implemented ideally by the author, or someone willing to write an addon mod for the compatability (bit harder though, as it'll require Mixins).

Best thing to do would be to request that the author adds support for Async Locator.

I'll close based on that, but please let me know if I got something wrong, or you can feel free to comment with a link to the request to the mod author for future reference 🙂
